import dotenv from 'dotenv';
import mongoose from 'mongoose';
import Restaurant from './models/Restaurant.js';
import connectDB from './config/db.js';

dotenv.config();

const seedRestaurants = async () => {
  try {
    await connectDB();

    await Restaurant.deleteMany({});

    const restaurants = [
      {
        name: 'Bella Napoli',
        cuisine: 'Italian',
        location: 'Downtown',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=60',
        rating: 4.8,
        description: 'Authentic Neapolitan cuisine with wood-fired pizzas and handmade pasta. Family recipes passed down through generations.',
        menu: [
          { name: 'Margherita Pizza', price: 399, description: 'San Marzano tomatoes, fresh mozzarella, basil, extra virgin olive oil' },
          { name: 'Quattro Formaggi Pizza', price: 499, description: 'Four cheese blend: mozzarella, gorgonzola, parmigiano, fontina' },
          { name: 'Spaghetti Carbonara', price: 449, description: 'Guanciale, pecorino romano, free-range eggs, black pepper' },
          { name: 'Fettuccine Alfredo', price: 479, description: 'Fresh fettuccine, butter, parmigiano reggiano cream sauce' },
          { name: 'Lasagna Bolognese', price: 549, description: 'Slow-cooked beef ragu, bechamel, fresh pasta sheets, parmigiano' },
          { name: 'Ravioli ai Funghi', price: 599, description: 'Wild mushroom stuffed ravioli, sage butter sauce, truffle oil' },
          { name: 'Osso Buco', price: 899, description: 'Braised veal shanks, saffron risotto, gremolata' },
          { name: 'Tiramisu', price: 249, description: 'Espresso-soaked ladyfingers, mascarpone cream, cocoa powder' },
          { name: 'Panna Cotta', price: 199, description: 'Vanilla bean custard, berry compote' },
          { name: 'Aperol Spritz', price: 299, description: 'Aperol, prosecco, soda, orange slice' },
        ],
      },
      {
        name: 'Golden Dragon',
        cuisine: 'Chinese',
        location: 'Chinatown',
        image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&auto=format&fit=crop&q=60',
        rating: 4.7,
        description: 'Authentic Szechuan and Cantonese cuisine. Spice levels from mild to fiery hot. Dim sum served daily.',
        menu: [
          { name: 'Kung Pao Chicken', price: 399, description: 'Wok-fried chicken, peanuts, dried chilies, Szechuan peppercorns' },
          { name: 'Mapo Tofu', price: 349, description: 'Silky tofu, ground pork, fermented black beans, chili oil' },
          { name: 'Peking Duck (Half)', price: 999, description: 'Crispy skin duck, pancakes, scallions, hoisin sauce' },
          { name: 'Dim Sum Platter', price: 599, description: 'Har gow, siu mai, char siu bao, spring rolls, pot stickers' },
          { name: 'Sweet and Sour Pork', price: 429, description: 'Crispy pork, bell peppers, pineapple, tangy sauce' },
          { name: 'Yang Chow Fried Rice', price: 329, description: 'BBQ pork, shrimp, eggs, peas, scallions' },
          { name: 'Hot and Sour Soup', price: 199, description: 'Tofu, mushrooms, bamboo shoots, egg ribbons, vinegar' },
          { name: 'General Tso\'s Chicken', price: 429, description: 'Crispy chicken, dried chilies, sweet and spicy sauce' },
          { name: 'Mongolian Beef', price: 499, description: 'Tender beef, scallions, garlic, ginger, hoisin sauce' },
          { name: 'Chow Mein', price: 299, description: 'Stir-fried noodles, vegetables, choice of protein' },
        ],
      },
      {
        name: 'Taj Palace',
        cuisine: 'Indian',
        location: 'Little India',
        image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop&q=60',
        rating: 4.9,
        description: 'Royal Indian cuisine from across the subcontinent. Tandoor specialties, rich curries, and aromatic biryanis.',
        menu: [
          { name: 'Butter Chicken', price: 449, description: 'Tandoor-roasted chicken, tomato cream sauce, fenugreek, butter' },
          { name: 'Chicken Tikka Masala', price: 449, description: 'Marinated chicken, spiced curry, yogurt, garam masala' },
          { name: 'Lamb Rogan Josh', price: 549, description: 'Kashmiri lamb curry, yogurt, aromatic spices, saffron' },
          { name: 'Palak Paneer', price: 349, description: 'Cottage cheese, creamy spinach, garlic, ginger, spices' },
          { name: 'Chicken Biryani', price: 399, description: 'Basmati rice, marinated chicken, saffron, whole spices, raita' },
          { name: 'Tandoori Mixed Grill', price: 699, description: 'Chicken tikka, lamb kebab, fish tikka, tandoori shrimp' },
          { name: 'Samosa Chat', price: 149, description: 'Crispy samosas, chickpeas, yogurt, tamarind chutney, spices' },
          { name: 'Garlic Naan', price: 49, description: 'Fresh-baked flatbread, garlic butter, cilantro' },
          { name: 'Mango Lassi', price: 99, description: 'Sweet yogurt drink, fresh mango, cardamom' },
          { name: 'Gulab Jamun', price: 129, description: 'Fried milk dumplings, rose-cardamom syrup' },
        ],
      },
      {
        name: 'The Burger Lab',
        cuisine: 'American',
        location: 'Westside',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=60',
        rating: 4.6,
        description: 'Gourmet burgers with house-ground beef. Craft beers on tap. Loaded fries and milkshakes.',
        menu: [
          { name: 'Classic Cheeseburger', price: 349, description: 'Angus beef, aged cheddar, lettuce, tomato, onion, special sauce' },
          { name: 'Bacon BBQ Burger', price: 429, description: 'Double beef patty, crispy bacon, cheddar, BBQ sauce, onion rings' },
          { name: 'Mushroom Swiss Burger', price: 379, description: 'Sautéed mushrooms, Swiss cheese, caramelized onions, truffle aioli' },
          { name: 'Spicy Jalapeño Burger', price: 379, description: 'Pepper jack cheese, jalapeños, chipotle mayo, crispy onions' },
          { name: 'Veggie Burger', price: 299, description: 'House-made black bean patty, avocado, sprouts, chipotle aioli' },
          { name: 'Loaded Cheese Fries', price: 249, description: 'Crispy fries, cheddar sauce, bacon bits, scallions, sour cream' },
          { name: 'Sweet Potato Fries', price: 179, description: 'Crispy sweet potato fries, chipotle aioli' },
          { name: 'Onion Rings', price: 199, description: 'Beer-battered onion rings, ranch dressing' },
          { name: 'Buffalo Wings', price: 329, description: '8 wings, buffalo sauce, blue cheese dressing, celery' },
          { name: 'Chocolate Milkshake', price: 199, description: 'Premium ice cream, whipped cream, chocolate syrup' },
        ],
      },
      {
        name: 'Tokyo Sushi Bar',
        cuisine: 'Japanese',
        location: 'Eastside',
        image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600&auto=format&fit=crop&q=60',
        rating: 4.9,
        description: 'Omakase-style sushi with the freshest fish. Traditional Japanese izakaya dishes and premium sake.',
        menu: [
          { name: 'Omakase (Chef\'s Choice)', price: 1999, description: '12 pieces of chef-selected nigiri, miso soup, salad' },
          { name: 'Sashimi Deluxe', price: 999, description: 'Tuna, salmon, yellowtail, octopus, sea urchin, fresh wasabi' },
          { name: 'Dragon Roll', price: 499, description: 'Shrimp tempura, eel, avocado, cucumber, eel sauce' },
          { name: 'Spicy Tuna Roll', price: 379, description: 'Chopped tuna, scallions, spicy mayo, sesame seeds' },
          { name: 'Rainbow Roll', price: 449, description: 'California roll topped with tuna, salmon, yellowtail, avocado' },
          { name: 'Salmon Nigiri (2 pcs)', price: 249, description: 'Fresh Norwegian salmon, sushi rice, wasabi' },
          { name: 'Tuna Nigiri (2 pcs)', price: 279, description: 'Premium bluefin tuna, sushi rice, wasabi' },
          { name: 'Chicken Teriyaki', price: 429, description: 'Grilled chicken thigh, teriyaki glaze, steamed rice, vegetables' },
          { name: 'Tempura Udon', price: 399, description: 'Thick noodles, dashi broth, shrimp and vegetable tempura' },
          { name: 'Mochi Ice Cream', price: 199, description: 'Green tea, mango, and strawberry flavors (3 pieces)' },
        ],
      },
      {
        name: 'La Taqueria',
        cuisine: 'Mexican',
        location: 'Mission District',
        image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=60',
        rating: 4.7,
        description: 'Authentic street tacos and burritos. Fresh ingredients, homemade salsas, and traditional Mexican flavors.',
        menu: [
          { name: 'Carne Asada Tacos (3)', price: 360, description: 'Grilled steak, cilantro, onions, lime, corn tortillas' },
          { name: 'Al Pastor Tacos (3)', price: 360, description: 'Marinated pork, pineapple, cilantro, onions, corn tortillas' },
          { name: 'Fish Tacos (3)', price: 390, description: 'Beer-battered fish, cabbage, pico de gallo, chipotle mayo' },
          { name: 'Super Burrito', price: 330, description: 'Rice, beans, cheese, sour cream, guacamole, choice of meat' },
          { name: 'Quesadilla Suprema', price: 300, description: 'Flour tortilla, melted cheese, choice of meat, guacamole, sour cream' },
          { name: 'Nachos Supreme', price: 390, description: 'Tortilla chips, cheese sauce, beans, jalapeños, sour cream, guacamole' },
          { name: 'Chicken Enchiladas', price: 420, description: 'Corn tortillas, shredded chicken, red sauce, cheese, rice, beans' },
          { name: 'Guacamole & Chips', price: 240, description: 'Fresh-made guacamole, crispy tortilla chips, salsa verde' },
          { name: 'Churros', price: 180, description: 'Fried dough pastry, cinnamon sugar, chocolate sauce' },
          { name: 'Horchata', price: 120, description: 'Traditional rice drink, cinnamon, vanilla' },
        ],
      },
      {
        name: 'Mediterranean Breeze',
        cuisine: 'Mediterranean',
        location: 'Harbor District',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=60',
        rating: 4.8,
        description: 'Fresh Mediterranean cuisine. Grilled meats, fresh seafood, and vibrant mezze platters.',
        menu: [
          { name: 'Mixed Mezze Platter', price: 510, description: 'Hummus, baba ganoush, falafel, dolmas, tzatziki, pita bread' },
          { name: 'Lamb Gyro', price: 390, description: 'Spit-roasted lamb, tzatziki, tomatoes, onions, pita wrap' },
          { name: 'Chicken Shawarma', price: 360, description: 'Marinated chicken, garlic sauce, pickles, pita wrap' },
          { name: 'Falafel Plate', price: 330, description: 'Crispy falafel, hummus, tahini, salad, rice, pita' },
          { name: 'Grilled Salmon', price: 600, description: 'Mediterranean-spiced salmon, lemon, olive oil, roasted vegetables' },
          { name: 'Lamb Kebabs', price: 570, description: 'Marinated lamb skewers, rice pilaf, grilled vegetables, tzatziki' },
          { name: 'Greek Salad', price: 300, description: 'Tomatoes, cucumbers, olives, feta, red onion, olive oil, oregano' },
          { name: 'Spanakopita', price: 270, description: 'Spinach and feta phyllo pastry, side salad' },
          { name: 'Baklava', price: 210, description: 'Phyllo pastry, walnuts, honey syrup, pistachios' },
          { name: 'Turkish Coffee', price: 120, description: 'Strong coffee, cardamom, served traditional style' },
        ],
      },
      {
        name: 'Thai Orchid',
        cuisine: 'Thai',
        location: 'University District',
        image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&auto=format&fit=crop&q=60',
        rating: 4.8,
        description: 'Authentic Thai flavors. Aromatic curries, stir-fries, and traditional noodle dishes. Spice levels customizable.',
        menu: [
          { name: 'Pad Thai', price: 390, description: 'Rice noodles, shrimp, tofu, egg, peanuts, bean sprouts, tamarind sauce' },
          { name: 'Green Curry', price: 420, description: 'Coconut milk, Thai basil, bamboo shoots, eggplant, choice of protein' },
          { name: 'Massaman Curry', price: 450, description: 'Rich curry, potatoes, peanuts, onions, beef or chicken' },
          { name: 'Tom Yum Soup', price: 270, description: 'Hot and sour soup, lemongrass, galangal, mushrooms, shrimp' },
          { name: 'Pad See Ew', price: 360, description: 'Wide rice noodles, Chinese broccoli, egg, sweet soy sauce' },
          { name: 'Thai Basil Chicken', price: 390, description: 'Ground chicken, Thai basil, chilies, garlic, jasmine rice' },
          { name: 'Spring Rolls (4)', price: 210, description: 'Vegetable spring rolls, sweet chili sauce' },
          { name: 'Satay Skewers (4)', price: 300, description: 'Grilled chicken, peanut sauce, cucumber relish' },
          { name: 'Mango Sticky Rice', price: 240, description: 'Sweet sticky rice, fresh mango, coconut cream' },
          { name: 'Thai Iced Tea', price: 150, description: 'Sweet tea, condensed milk, ice' },
        ],
      },
      {
        name: 'Le Petit Bistro',
        cuisine: 'French',
        location: 'French Quarter',
        image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&auto=format&fit=crop&q=60',
        rating: 4.9,
        description: 'Classic French bistro cuisine. Coq au vin, duck confit, and fine wines. Parisian ambiance.',
        menu: [
          { name: 'French Onion Soup', price: 270, description: 'Caramelized onions, beef broth, gruyère cheese, toasted baguette' },
          { name: 'Escargots de Bourgogne', price: 390, description: 'Burgundy snails, garlic herb butter, baguette' },
          { name: 'Coq au Vin', price: 690, description: 'Braised chicken, red wine, mushrooms, pearl onions, bacon' },
          { name: 'Duck Confit', price: 810, description: 'Slow-cooked duck leg, potato gratin, green beans' },
          { name: 'Steak Frites', price: 870, description: 'Grilled ribeye, herb butter, hand-cut fries, mixed greens' },
          { name: 'Bouillabaisse', price: 750, description: 'Provençal fish stew, saffron, rouille, crusty bread' },
          { name: 'Ratatouille', price: 510, description: 'Provençal vegetables, tomato sauce, herbs de Provence' },
          { name: 'Crème Brûlée', price: 270, description: 'Vanilla custard, caramelized sugar, fresh berries' },
          { name: 'Chocolate Mousse', price: 240, description: 'Rich dark chocolate, whipped cream, chocolate shavings' },
          { name: 'House Wine (Glass)', price: 300, description: 'Selection of French red or white wines' },
        ],
      },
      {
        name: 'Seoul Kitchen',
        cuisine: 'Korean',
        location: 'Koreatown',
        image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=60',
        rating: 4.7,
        description: 'Korean BBQ and traditional dishes. Kimchi made in-house daily. Authentic banchan and soju cocktails.',
        menu: [
          { name: 'Korean BBQ Combo', price: 990, description: 'Bulgogi, galbi, pork belly, rice, banchan (serves 2)' },
          { name: 'Bibimbap', price: 420, description: 'Mixed rice bowl, vegetables, egg, gochujang, choice of protein' },
          { name: 'Kimchi Jjigae', price: 390, description: 'Kimchi stew, pork belly, tofu, rice, banchan' },
          { name: 'Japchae', price: 360, description: 'Glass noodles, vegetables, sesame oil, soy sauce' },
          { name: 'Korean Fried Chicken', price: 480, description: 'Double-fried chicken, sweet chili glaze, pickled radish' },
          { name: 'Bulgogi', price: 510, description: 'Marinated beef, onions, sesame, rice, banchan' },
          { name: 'Tteokbokki', price: 300, description: 'Spicy rice cakes, fish cakes, gochujang sauce' },
          { name: 'Mandu (Dumplings)', price: 270, description: 'Pan-fried dumplings, soy dipping sauce (8 pieces)' },
          { name: 'Hotteok', price: 180, description: 'Sweet Korean pancake, brown sugar, cinnamon, nuts' },
          { name: 'Soju Cocktail', price: 270, description: 'Flavored soju, fresh fruit, soda' },
        ],
      },
      {
        name: 'Pizza Romana',
        cuisine: 'Italian',
        location: 'North End',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=60',
        rating: 4.8,
        description: 'Roman-style pizza al taglio and traditional Roman dishes. Thin, crispy crust baked in electric ovens.',
        menu: [
          { name: 'Pizza Bianca', price: 270, description: 'White pizza, olive oil, sea salt, rosemary' },
          { name: 'Pizza Marinara', price: 330, description: 'Tomato sauce, garlic, oregano, olive oil' },
          { name: 'Pizza Prosciutto e Rucola', price: 480, description: 'Prosciutto di Parma, arugula, shaved parmigiano' },
          { name: 'Supplì (Roman Rice Balls)', price: 240, description: 'Fried rice balls, mozzarella, tomato sauce (4 pieces)' },
          { name: 'Cacio e Pepe', price: 450, description: 'Pecorino romano, black pepper, pasta water emulsion' },
          { name: 'Amatriciana', price: 480, description: 'Guanciale, tomato sauce, pecorino, chili flakes' },
          { name: 'Saltimbocca alla Romana', price: 660, description: 'Veal, prosciutto, sage, white wine sauce' },
          { name: 'Carciofi alla Giudia', price: 360, description: 'Jewish-style fried artichokes, lemon' },
          { name: 'Gelato (3 scoops)', price: 210, description: 'Pistachio, stracciatella, hazelnut' },
          { name: 'Espresso', price: 90, description: 'Traditional Italian espresso' },
        ],
      },
      {
        name: 'Pho Saigon',
        cuisine: 'Vietnamese',
        location: 'Little Saigon',
        image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=60',
        rating: 4.7,
        description: 'Authentic Vietnamese pho and banh mi. Slow-simmered broths and fresh herbs. Family recipes since 1985.',
        menu: [
          { name: 'Pho Bo (Beef Pho)', price: 360, description: 'Rice noodles, rare beef, brisket, tendon, fresh herbs, lime' },
          { name: 'Pho Ga (Chicken Pho)', price: 330, description: 'Rice noodles, chicken breast, fresh herbs, lime' },
          { name: 'Bun Bo Hue', price: 390, description: 'Spicy beef noodle soup, lemongrass, pork hock, blood cake' },
          { name: 'Banh Mi Thit', price: 270, description: 'Vietnamese pork sandwich, pate, pickled vegetables, cilantro, jalapeño' },
          { name: 'Banh Mi Ga', price: 270, description: 'Grilled chicken sandwich, pickled vegetables, cilantro, jalapeño' },
          { name: 'Bun Thit Nuong', price: 360, description: 'Vermicelli, grilled pork, lettuce, herbs, fish sauce, peanuts' },
          { name: 'Spring Rolls (2)', price: 210, description: 'Fresh rice paper, shrimp, pork, vermicelli, herbs, peanut sauce' },
          { name: 'Fried Spring Rolls (4)', price: 240, description: 'Crispy rolls, ground pork, vegetables, fish sauce' },
          { name: 'Vietnamese Iced Coffee', price: 150, description: 'Strong coffee, condensed milk, ice' },
          { name: 'Che Ba Mau', price: 180, description: 'Three-color dessert, beans, jelly, coconut milk' },
        ],
      },
    ];

    await Restaurant.insertMany(restaurants);
    console.log('Seed restaurants created successfully');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding restaurants:', error);
    process.exit(1);
  }
};

seedRestaurants();
